### ISSUE TITLE
Créer de jolis vues ! 

### ISSUE THREAD

**Issue by aroquemaurel** [aroquemaurel/Toulouse-Musees#15]
- Utilisation de bootstrap
- Modification des formulaires comme nécessaire

**Comment by NitriKx** [comment]
J'espère qu'elles sont jolies :p

**Comment by aroquemaurel** [comment]
Bah oui, of course, c'est du boostrap :-)

**Comment by NitriKx** [comment]
C'est pas parce-qu'il y a bootstrap que c'est beau :-p

**Comment by aroquemaurel** [comment]
Ouais, mais là c'est joli ! :-)
